export type AdmissionStatus =
  "Pending" | "Admitted" | "Transferred" | "Discharge Pending" | "Discharged";
export type BedStatus =
  "Available" | "Occupied" | "Reserved" | "Cleaning" | "Maintenance" | "Out of Service";

export const admissionRequests = [
  {
    id: "req-241",
    patient: "Hodan Ahmed",
    patientNumber: "GGH-PAT-000151",
    requestedBy: "Dr. Hassan Ismail",
    department: "Emergency",
    reason: "Observation after acute asthma episode",
    diagnosis: "Acute asthma exacerbation",
    priority: "Emergency",
    requestedWard: "Medical Ward",
    requestedAt: "10:56",
  },
  {
    id: "req-240",
    patient: "Abdiqadir Osman",
    patientNumber: "GGH-PAT-000149",
    requestedBy: "Dr. Hawa Omar",
    department: "Pediatrics",
    reason: "Dehydration requiring observation",
    diagnosis: "Acute gastroenteritis",
    priority: "Urgent",
    requestedWard: "Pediatric Ward",
    requestedAt: "10:34",
  },
  {
    id: "req-239",
    patient: "Fadumo Ali",
    patientNumber: "GGH-PAT-000146",
    requestedBy: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    reason: "Monitoring and medication adjustment",
    diagnosis: "Uncontrolled hypertension",
    priority: "Routine",
    requestedWard: "Medical Ward",
    requestedAt: "09:48",
  },
] as const;

export const admissions = [
  {
    id: "adm-241",
    number: "GGH-ADM-2026-000241",
    patientId: "p-00133",
    patient: "Sahra Nur",
    patientNumber: "GGH-PAT-000133",
    ward: "Medical Ward",
    wardId: "medical",
    room: "Room 2",
    bed: "MED-02-A",
    doctor: "Dr. Ahmed Yusuf",
    admittedAt: "20 Aug 2026",
    los: "2d 14h",
    diagnosis: "Febrile illness",
    status: "Admitted" as AdmissionStatus,
    priority: "Routine",
  },
  {
    id: "adm-240",
    number: "GGH-ADM-2026-000240",
    patientId: "p-00131",
    patient: "Mohamed Ali",
    patientNumber: "GGH-PAT-000131",
    ward: "Pediatric Ward",
    wardId: "pediatrics",
    room: "Room 1",
    bed: "PED-01-B",
    doctor: "Dr. Hawa Omar",
    admittedAt: "21 Aug 2026",
    los: "1d 7h",
    diagnosis: "Acute gastroenteritis",
    status: "Discharge Pending" as AdmissionStatus,
    priority: "Urgent",
  },
  {
    id: "adm-238",
    number: "GGH-ADM-2026-000238",
    patientId: "p-00138",
    patient: "Maryan Ibrahim",
    patientNumber: "GGH-PAT-000138",
    ward: "Maternity Ward",
    wardId: "maternity",
    room: "Room 3",
    bed: "MAT-03-A",
    doctor: "Dr. Hawa Omar",
    admittedAt: "18 Aug 2026",
    los: "4d 2h",
    diagnosis: "Post-delivery observation",
    status: "Admitted" as AdmissionStatus,
    priority: "Routine",
  },
  {
    id: "adm-236",
    number: "GGH-ADM-2026-000236",
    patientId: "p-00142",
    patient: "Yusuf Abdullahi",
    patientNumber: "GGH-PAT-000142",
    ward: "Surgical Ward",
    wardId: "surgical",
    room: "Room 1",
    bed: "SUR-01-A",
    doctor: "Dr. Ahmed Yusuf",
    admittedAt: "16 Aug 2026",
    los: "6d 5h",
    diagnosis: "Post-operative recovery",
    status: "Transferred" as AdmissionStatus,
    priority: "Urgent",
  },
] as const;

export const wards = [
  {
    id: "medical",
    name: "Medical Ward",
    code: "MED",
    department: "General Medicine",
    total: 24,
    occupied: 19,
    available: 3,
    cleaning: 1,
    maintenance: 1,
    rate: 79,
  },
  {
    id: "pediatrics",
    name: "Pediatric Ward",
    code: "PED",
    department: "Pediatrics",
    total: 18,
    occupied: 11,
    available: 6,
    cleaning: 1,
    maintenance: 0,
    rate: 61,
  },
  {
    id: "maternity",
    name: "Maternity Ward",
    code: "MAT",
    department: "Obstetrics & Gynecology",
    total: 20,
    occupied: 15,
    available: 4,
    cleaning: 1,
    maintenance: 0,
    rate: 75,
  },
  {
    id: "surgical",
    name: "Surgical Ward",
    code: "SUR",
    department: "Surgery",
    total: 16,
    occupied: 9,
    available: 5,
    cleaning: 1,
    maintenance: 1,
    rate: 56,
  },
] as const;

export const beds = [
  {
    id: "bed-med-02-a",
    code: "MED-02-A",
    ward: "Medical Ward",
    room: "Room 2",
    status: "Occupied" as BedStatus,
    patient: "Sahra Nur",
    patientNumber: "GGH-PAT-000133",
    doctor: "Dr. Ahmed Yusuf",
    los: "2d 14h",
    isolation: false,
  },
  {
    id: "bed-med-02-b",
    code: "MED-02-B",
    ward: "Medical Ward",
    room: "Room 2",
    status: "Available" as BedStatus,
    patient: "",
    patientNumber: "",
    doctor: "",
    los: "",
    isolation: false,
  },
  {
    id: "bed-med-03-a",
    code: "MED-03-A",
    ward: "Medical Ward",
    room: "Room 3",
    status: "Cleaning" as BedStatus,
    patient: "",
    patientNumber: "",
    doctor: "",
    los: "",
    isolation: false,
  },
  {
    id: "bed-ped-01-b",
    code: "PED-01-B",
    ward: "Pediatric Ward",
    room: "Room 1",
    status: "Occupied" as BedStatus,
    patient: "Mohamed Ali",
    patientNumber: "GGH-PAT-000131",
    doctor: "Dr. Hawa Omar",
    los: "1d 7h",
    isolation: false,
  },
  {
    id: "bed-ped-01-c",
    code: "PED-01-C",
    ward: "Pediatric Ward",
    room: "Room 1",
    status: "Available" as BedStatus,
    patient: "",
    patientNumber: "",
    doctor: "",
    los: "",
    isolation: false,
  },
  {
    id: "bed-mat-03-a",
    code: "MAT-03-A",
    ward: "Maternity Ward",
    room: "Room 3",
    status: "Occupied" as BedStatus,
    patient: "Maryan Ibrahim",
    patientNumber: "GGH-PAT-000138",
    doctor: "Dr. Hawa Omar",
    los: "4d 2h",
    isolation: false,
  },
  {
    id: "bed-sur-01-a",
    code: "SUR-01-A",
    ward: "Surgical Ward",
    room: "Room 1",
    status: "Occupied" as BedStatus,
    patient: "Yusuf Abdullahi",
    patientNumber: "GGH-PAT-000142",
    doctor: "Dr. Ahmed Yusuf",
    los: "6d 5h",
    isolation: true,
  },
  {
    id: "bed-sur-01-b",
    code: "SUR-01-B",
    ward: "Surgical Ward",
    room: "Room 1",
    status: "Maintenance" as BedStatus,
    patient: "",
    patientNumber: "",
    doctor: "",
    los: "",
    isolation: false,
  },
] as const;

export const admissionActivity = [
  "Bed MED-02-A assigned to Sahra Nur · 18 min ago",
  "Discharge prepared for Mohamed Ali · 32 min ago",
  "Bed SUR-01-B placed in maintenance · 1 hr ago",
];
