export type AppointmentStatus =
  | "Scheduled"
  | "Confirmed"
  | "Checked In"
  | "Waiting"
  | "In Consultation"
  | "Completed"
  | "Cancelled"
  | "No Show";

export const appointmentRows = [
  {
    id: "APT-02481",
    patientId: "p-00128",
    patient: "Amina Hassan",
    patientNumber: "GGH-PAT-000128",
    phone: "+252 90 411 2840",
    doctor: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    date: "22 Aug 2026",
    time: "08:30",
    type: "Follow-up",
    status: "Completed" as AppointmentStatus,
    wait: "—",
  },
  {
    id: "APT-02482",
    patientId: "p-00131",
    patient: "Mohamed Ali",
    patientNumber: "GGH-PAT-000131",
    phone: "+252 90 522 7812",
    doctor: "Dr. Hawa Omar",
    department: "Pediatrics",
    date: "22 Aug 2026",
    time: "09:00",
    type: "New consultation",
    status: "In Consultation" as AppointmentStatus,
    wait: "18 min",
  },
  {
    id: "APT-02483",
    patientId: "p-00133",
    patient: "Sahra Nur",
    patientNumber: "GGH-PAT-000133",
    phone: "+252 90 633 1108",
    doctor: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    date: "22 Aug 2026",
    time: "09:30",
    type: "Walk-in",
    status: "Waiting" as AppointmentStatus,
    wait: "47 min",
  },
  {
    id: "APT-02484",
    patientId: "p-00134",
    patient: "Abdi Warsame",
    patientNumber: "GGH-PAT-000134",
    phone: "+252 90 744 9031",
    doctor: "Dr. Hassan Ismail",
    department: "Emergency",
    date: "22 Aug 2026",
    time: "10:00",
    type: "Emergency",
    status: "Checked In" as AppointmentStatus,
    wait: "12 min",
  },
  {
    id: "APT-02485",
    patientId: "p-00138",
    patient: "Maryan Ibrahim",
    patientNumber: "GGH-PAT-000138",
    phone: "+252 90 855 6220",
    doctor: "Dr. Hawa Omar",
    department: "Obstetrics & Gynecology",
    date: "22 Aug 2026",
    time: "10:30",
    type: "Review",
    status: "Confirmed" as AppointmentStatus,
    wait: "—",
  },
  {
    id: "APT-02486",
    patientId: "p-00142",
    patient: "Yusuf Abdullahi",
    patientNumber: "GGH-PAT-000142",
    phone: "+252 90 966 4710",
    doctor: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    date: "22 Aug 2026",
    time: "11:00",
    type: "New consultation",
    status: "Scheduled" as AppointmentStatus,
    wait: "—",
  },
  {
    id: "APT-02487",
    patientId: "p-00145",
    patient: "Hawo Omar",
    patientNumber: "GGH-PAT-000145",
    phone: "+252 90 177 3084",
    doctor: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    date: "22 Aug 2026",
    time: "11:30",
    type: "Follow-up",
    status: "No Show" as AppointmentStatus,
    wait: "—",
  },
];

export const appointmentDoctors = [
  {
    name: "Dr. Ahmed Yusuf",
    specialty: "General Medicine",
    department: "General Medicine",
    next: "Today · 11:00",
    availability: "Available",
  },
  {
    name: "Dr. Hawa Omar",
    specialty: "Pediatrics",
    department: "Pediatrics",
    next: "Today · 14:00",
    availability: "Available",
  },
  {
    name: "Dr. Hassan Ismail",
    specialty: "Emergency Medicine",
    department: "Emergency",
    next: "On duty",
    availability: "On duty",
  },
];
