export type InvoiceStatus = "Draft" | "Issued" | "Partially Paid" | "Paid" | "Overdue" | "Void";
export type PaymentStatus = "Completed" | "Reversed" | "Refunded";

export const hospitalCurrency = "USD";
export function formatMoney(value: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: hospitalCurrency }).format(
    value,
  );
}

export const invoices = [
  {
    id: "inv-481",
    number: "GGH-INV-2026-000481",
    patientId: "p-00133",
    patient: "Sahra Nur",
    patientNumber: "GGH-PAT-000133",
    visit: "VIS-00883",
    department: "General Medicine",
    date: "22 Aug 2026",
    total: 54.5,
    paid: 20,
    balance: 34.5,
    status: "Partially Paid" as InvoiceStatus,
    createdBy: "Fatima Ali",
  },
  {
    id: "inv-480",
    number: "GGH-INV-2026-000480",
    patientId: "p-00134",
    patient: "Abdi Warsame",
    patientNumber: "GGH-PAT-000134",
    visit: "VIS-00884",
    department: "Emergency",
    date: "22 Aug 2026",
    total: 118,
    paid: 118,
    balance: 0,
    status: "Paid" as InvoiceStatus,
    createdBy: "Mohamed Noor",
  },
  {
    id: "inv-479",
    number: "GGH-INV-2026-000479",
    patientId: "p-00131",
    patient: "Mohamed Ali",
    patientNumber: "GGH-PAT-000131",
    visit: "VIS-00885",
    department: "Pediatrics",
    date: "22 Aug 2026",
    total: 36,
    paid: 0,
    balance: 36,
    status: "Issued" as InvoiceStatus,
    createdBy: "Fatima Ali",
  },
  {
    id: "inv-478",
    number: "GGH-INV-2026-000478",
    patientId: "p-00138",
    patient: "Maryan Ibrahim",
    patientNumber: "GGH-PAT-000138",
    visit: "VIS-00886",
    department: "Obstetrics & Gynecology",
    date: "21 Aug 2026",
    total: 82.5,
    paid: 82.5,
    balance: 0,
    status: "Paid" as InvoiceStatus,
    createdBy: "Mohamed Noor",
  },
  {
    id: "inv-476",
    number: "GGH-INV-2026-000476",
    patientId: "p-00142",
    patient: "Yusuf Abdullahi",
    patientNumber: "GGH-PAT-000142",
    visit: "VIS-00887",
    department: "General Medicine",
    date: "19 Aug 2026",
    total: 145,
    paid: 0,
    balance: 145,
    status: "Overdue" as InvoiceStatus,
    createdBy: "Fatima Ali",
  },
] as const;

export const invoiceItems = [
  {
    service: "General consultation",
    category: "Consultation",
    quantity: 1,
    unitPrice: 15,
    discount: 0,
    total: 15,
    source: "Clinical",
    reference: "VIS-00883",
  },
  {
    service: "Complete blood count",
    category: "Laboratory",
    quantity: 1,
    unitPrice: 8,
    discount: 0,
    total: 8,
    source: "Laboratory",
    reference: "GGH-LAB-2026-000184",
  },
  {
    service: "Paracetamol 500 mg",
    category: "Pharmacy",
    quantity: 15,
    unitPrice: 0.08,
    discount: 0,
    total: 1.2,
    source: "Pharmacy",
    reference: "GGH-RX-2026-000481",
  },
  {
    service: "Observation bed",
    category: "Admission",
    quantity: 1,
    unitPrice: 30,
    discount: 0,
    total: 30,
    source: "Admission",
    reference: "ADM-0082",
  },
] as const;

export const payments = [
  {
    id: "pay-584",
    number: "GGH-PAY-2026-000584",
    receipt: "GGH-REC-2026-000584",
    patient: "Abdi Warsame",
    invoice: "GGH-INV-2026-000480",
    amount: 118,
    method: "Mobile Money",
    reference: "ZAAD-883104",
    cashier: "Mohamed Noor",
    date: "10:48",
    status: "Completed" as PaymentStatus,
  },
  {
    id: "pay-583",
    number: "GGH-PAY-2026-000583",
    receipt: "GGH-REC-2026-000583",
    patient: "Sahra Nur",
    invoice: "GGH-INV-2026-000481",
    amount: 20,
    method: "Cash",
    reference: "—",
    cashier: "Fatima Ali",
    date: "10:35",
    status: "Completed" as PaymentStatus,
  },
  {
    id: "pay-582",
    number: "GGH-PAY-2026-000582",
    receipt: "GGH-REC-2026-000582",
    patient: "Maryan Ibrahim",
    invoice: "GGH-INV-2026-000478",
    amount: 82.5,
    method: "Cash",
    reference: "—",
    cashier: "Mohamed Noor",
    date: "09:55",
    status: "Completed" as PaymentStatus,
  },
] as const;

export const billingServices = [
  {
    code: "CON-001",
    name: "General consultation",
    category: "Consultation",
    department: "General Medicine",
    price: 15,
    active: true,
  },
  {
    code: "LAB-001",
    name: "Complete blood count",
    category: "Laboratory",
    department: "Laboratory",
    price: 8,
    active: true,
  },
  {
    code: "LAB-004",
    name: "Malaria parasite test",
    category: "Laboratory",
    department: "Laboratory",
    price: 5,
    active: true,
  },
  {
    code: "ADM-001",
    name: "Observation bed",
    category: "Admission",
    department: "Admissions",
    price: 30,
    active: true,
  },
  {
    code: "PROC-003",
    name: "Wound dressing",
    category: "Procedure",
    department: "Outpatient",
    price: 12,
    active: true,
  },
];

export const revenueTrend = [
  { day: "18 Aug", value: 820 },
  { day: "19 Aug", value: 1120 },
  { day: "20 Aug", value: 960 },
  { day: "21 Aug", value: 1380 },
  { day: "22 Aug", value: 1240 },
];
