export type PrescriptionStatus =
  | "Sent to Pharmacy"
  | "In Review"
  | "Ready to Dispense"
  | "Partially Dispensed"
  | "Dispensed"
  | "Needs Clarification";
export type StockStatus = "In Stock" | "Low Stock" | "Out of Stock" | "Expiring Soon" | "Expired";

export const pharmacyPrescriptions = [
  {
    id: "rx-481",
    number: "GGH-RX-2026-000481",
    patientId: "p-00133",
    patient: "Sahra Nur",
    patientNumber: "GGH-PAT-000133",
    age: 34,
    gender: "Female",
    allergies: "Penicillin — Severe",
    doctor: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    medicines: 3,
    created: "10:42",
    priority: "Urgent",
    status: "In Review" as PrescriptionStatus,
  },
  {
    id: "rx-482",
    number: "GGH-RX-2026-000482",
    patientId: "p-00134",
    patient: "Abdi Warsame",
    patientNumber: "GGH-PAT-000134",
    age: 61,
    gender: "Male",
    allergies: "No known allergies",
    doctor: "Dr. Hassan Ismail",
    department: "Emergency",
    medicines: 2,
    created: "10:36",
    priority: "STAT",
    status: "Ready to Dispense" as PrescriptionStatus,
  },
  {
    id: "rx-479",
    number: "GGH-RX-2026-000479",
    patientId: "p-00131",
    patient: "Mohamed Ali",
    patientNumber: "GGH-PAT-000131",
    age: 8,
    gender: "Male",
    allergies: "No known allergies",
    doctor: "Dr. Hawa Omar",
    department: "Pediatrics",
    medicines: 2,
    created: "09:48",
    priority: "Routine",
    status: "Partially Dispensed" as PrescriptionStatus,
  },
  {
    id: "rx-477",
    number: "GGH-RX-2026-000477",
    patientId: "p-00138",
    patient: "Maryan Ibrahim",
    patientNumber: "GGH-PAT-000138",
    age: 28,
    gender: "Female",
    allergies: "Sulfa — Mild",
    doctor: "Dr. Hawa Omar",
    department: "Obstetrics & Gynecology",
    medicines: 1,
    created: "09:12",
    priority: "Routine",
    status: "Dispensed" as PrescriptionStatus,
  },
  {
    id: "rx-475",
    number: "GGH-RX-2026-000475",
    patientId: "p-00142",
    patient: "Yusuf Abdullahi",
    patientNumber: "GGH-PAT-000142",
    age: 46,
    gender: "Male",
    allergies: "No known allergies",
    doctor: "Dr. Ahmed Yusuf",
    department: "General Medicine",
    medicines: 4,
    created: "08:52",
    priority: "Routine",
    status: "Needs Clarification" as PrescriptionStatus,
  },
] as const;

export const prescriptionItems = [
  {
    name: "Amoxicillin",
    generic: "Amoxicillin",
    strength: "500 mg",
    form: "Capsule",
    dose: "1 capsule",
    route: "Oral",
    frequency: "3 times daily",
    duration: "7 days",
    prescribed: 21,
    dispensed: 0,
    unit: "capsules",
    status: "Pending",
    stock: 84,
    batch: "AMX-2407",
    expiry: "2027-07-31",
    price: 0.28,
    instructions: "Take after food",
  },
  {
    name: "Paracetamol",
    generic: "Paracetamol",
    strength: "500 mg",
    form: "Tablet",
    dose: "1 tablet",
    route: "Oral",
    frequency: "Every 8 hours",
    duration: "5 days",
    prescribed: 15,
    dispensed: 15,
    unit: "tablets",
    status: "Dispensed",
    stock: 268,
    batch: "PCM-2410",
    expiry: "2028-10-31",
    price: 0.08,
    instructions: "Take with water",
  },
  {
    name: "Fasting glucose strips",
    generic: "Glucose test strips",
    strength: "50 strips",
    form: "Solution",
    dose: "As directed",
    route: "Topical",
    frequency: "As needed",
    duration: "30 days",
    prescribed: 1,
    dispensed: 0,
    unit: "pack",
    status: "Unavailable",
    stock: 0,
    batch: "GLU-2402",
    expiry: "2026-09-30",
    price: 5.5,
    instructions: "Use with approved glucometer",
  },
] as const;

export const medicines = [
  {
    code: "MED-000124",
    name: "Amoxicillin",
    generic: "Amoxicillin",
    category: "Antibiotics",
    form: "Capsule",
    strength: "500 mg",
    unit: "capsule",
    price: 0.28,
    stock: 84,
    minimum: 60,
    status: "In Stock" as StockStatus,
  },
  {
    code: "MED-000101",
    name: "Paracetamol",
    generic: "Paracetamol",
    category: "Analgesics",
    form: "Tablet",
    strength: "500 mg",
    unit: "tablet",
    price: 0.08,
    stock: 268,
    minimum: 100,
    status: "In Stock" as StockStatus,
  },
  {
    code: "MED-000139",
    name: "Artemether / Lumefantrine",
    generic: "ACT 20/120",
    category: "Antimalarials",
    form: "Tablet",
    strength: "20/120 mg",
    unit: "tablet",
    price: 0.45,
    stock: 28,
    minimum: 40,
    status: "Low Stock" as StockStatus,
  },
  {
    code: "MED-000118",
    name: "Metformin",
    generic: "Metformin HCl",
    category: "Antidiabetics",
    form: "Tablet",
    strength: "500 mg",
    unit: "tablet",
    price: 0.12,
    stock: 0,
    minimum: 50,
    status: "Out of Stock" as StockStatus,
  },
  {
    code: "MED-000143",
    name: "Ceftriaxone",
    generic: "Ceftriaxone sodium",
    category: "Antibiotics",
    form: "Injection",
    strength: "1 g",
    unit: "vial",
    price: 2.8,
    stock: 18,
    minimum: 20,
    status: "Expiring Soon" as StockStatus,
  },
] as const;

export const pharmacyBatches = [
  {
    medicine: "Ceftriaxone",
    code: "MED-000143",
    batch: "CFX-2401",
    available: 18,
    reserved: 4,
    expiry: "2026-09-14",
    days: 23,
    minimum: 20,
    status: "Expiring Soon" as StockStatus,
  },
  {
    medicine: "Artemether / Lumefantrine",
    code: "MED-000139",
    batch: "ALU-2404",
    available: 28,
    reserved: 0,
    expiry: "2027-04-30",
    days: 251,
    minimum: 40,
    status: "Low Stock" as StockStatus,
  },
  {
    medicine: "Amoxicillin",
    code: "MED-000124",
    batch: "AMX-2407",
    available: 84,
    reserved: 21,
    expiry: "2027-07-31",
    days: 343,
    minimum: 60,
    status: "In Stock" as StockStatus,
  },
  {
    medicine: "Metformin",
    code: "MED-000118",
    batch: "MET-2402",
    available: 0,
    reserved: 0,
    expiry: "2027-02-28",
    days: 195,
    minimum: 50,
    status: "Out of Stock" as StockStatus,
  },
] as const;

export const stockMovements = [
  {
    id: "mov-01",
    medicine: "Paracetamol",
    batch: "PCM-2410",
    type: "Dispense",
    quantity: -15,
    previous: 283,
    next: 268,
    reference: "GGH-RX-2026-000481",
    user: "Fatima Ali",
    time: "10:51",
  },
  {
    id: "mov-02",
    medicine: "Ceftriaxone",
    batch: "CFX-2401",
    type: "Adjustment Decrease",
    quantity: -2,
    previous: 20,
    next: 18,
    reference: "Physical count",
    user: "Mohamed Noor",
    time: "10:22",
  },
  {
    id: "mov-03",
    medicine: "Amoxicillin",
    batch: "AMX-2407",
    type: "Stock In",
    quantity: 60,
    previous: 24,
    next: 84,
    reference: "Opening balance",
    user: "Mohamed Noor",
    time: "09:44",
  },
  {
    id: "mov-04",
    medicine: "Artemether / Lumefantrine",
    batch: "ALU-2404",
    type: "Damaged",
    quantity: -4,
    previous: 32,
    next: 28,
    reference: "Damaged packaging",
    user: "Fatima Ali",
    time: "09:18",
  },
] as const;

export const pharmacyActivity = [
  "Prescription GGH-RX-2026-000481 moved to review · Fatima Ali · 8 min ago",
  "Stock adjusted: Ceftriaxone CFX-2401 · Mohamed Noor · 22 min ago",
  "Partial dispense completed for Mohamed Ali · Fatima Ali · 41 min ago",
];
